# Numpy
NumPy is a Python library, used for working with arrays. NumPy arrays called ndarray are stored at one continuous place in memory unlike lists in python, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science. NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])  #array as list
print(arr)
print(type(arr))

tup = np.array((2,3,5,6))  #tuple as array
print("I am tuple array",tup)

[1 2 3 4 5]
<class 'numpy.ndarray'>
I am tuple array [2 3 5 6]


In [5]:
import numpy as np

a = np.array(42)  #o dimension
b = np.array([1, 2, 3, 4, 5])  #1 dimension 
c = np.array([[1, 2, 3], [4, 5, 6]])  #2 dimension
d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])  #3 dimension array

print(a.ndim) #ndim tells about dimension of an array
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(d)

print(b[0]) #access 1st element

0
1
2
3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1


In [7]:
print(d[1:5])  #Slice elements from index 1 to index 5 

print(c.dtype) #provides datatype of an array

[[[ 7  8  9]
  [10 11 12]]]
int64


# copy vs view 
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [8]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [9]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [10]:
# Shape of an array
arr = np.array([1,2,3,4]) # 1D array with 4 elements, and its shape is (4,), meaning it has one axis with 4 elements.
print(arr.shape)

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])  #2 rows 4 columns so dim 2,4

print(arr.shape)

#Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:
a = np.array([1,2,3,4], ndmin = 5)
print(a)
print(a.shape)

#1D arrays are flat lists.

#2D arrays are like matrices (rows and columns).

#3D arrays are like a stack of matrices (layers, rows, columns).

#Higher-dimensional arrays have more axes (used in advanced applications).

(4,)
(2, 4)
[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


In [11]:
#Reshaping means changing the shape of an array.

#The shape of an array is the number of elements in each dimension.

#By reshaping we can add or remove dimensions or change number of elements in each dimension.

#Convert the following 1-D array with 12 elements into a 2-D array.
#The outermost dimension will have 4 arrays, each with 3 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
#Every NumPy array has the attribute base that returns None if the array owns the data. Otherwise, the base  attribute refers to the original object.
#copy returns none, view returns original data

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base) #view

[1 2 3 4 5 6 7 8]


In [13]:
#You are allowed to have one "unknown" dimension.

#Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

#Pass -1 as the value, and NumPy will calculate this number for you.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
#Flattening array means converting a multidimensional array into a 1D array.

#We can use reshape(-1) to do this.
arr= np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr.shape)

newarr = arr.reshape(-1)
print(newarr)
print(newarr.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[1 2 3 4 5 6 7 8]
(8,)


In [15]:
#iterating through arrays
arr = np.array([1, 2, 3])  #for 1D, loop will iterate through all elements one by one

for x in arr:
  print(x)

arr2 = np.array([[1,2,3],[4,5,6]])  #In a 2-D array it will go through all the rows
for x in arr2:
  print(x)

arr2a = np.array([[1, 2, 3], [4, 5, 6]]) #To return the actual values, the scalars, we have to iterate the arrays in each dimension.

for x in arr2a:
  for y in x:
    print(y)


arr3 = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

for x in arr3:
    for y in x:
        for z in y:
            print(z)

1
2
3
[1 2 3]
[4 5 6]
1
2
3
4
5
6
1
2
3
4
5
6
7
8
9
10
11
12


In [16]:
#The function nditer() is a helping function that can be used from very basic to very advanced iterations. 
#In basic for loops, iterating through each scalar of an array
#we need to use n for loops which can be difficult to write for arrays with very high dimensionality.
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [17]:
#Enumeration means mentioning sequence number of somethings one by one.

#Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

arr2 = np.array([[1,2,3],[4,5,6]])

for idx,x in np.ndenumerate(arr2):
    print(idx,x)

(0,) 1
(1,) 2
(2,) 3
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [22]:
#array concatenation
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

#arr = np.concatenate((arr1, arr2))
arr = np.concatenate((arr1, arr2), axis=0) #axis means concatenate along column we gave axis 0 cz there's no column yet the shape of these arrays is (3,)
print(arr)

[1 2 3 4 5 6]


In [23]:
#Join two 2-D arrays along rows (axis=1)
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [25]:
#Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

#We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)
#here if we had used concatenate() it would have give error.
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [26]:
#NumPy provides a helper function: hstack() to stack along rows.

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

#NumPy provides a helper function: vstack()  to stack along columns.
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

#NumPy provides a helper function: dstack() to stack along height, which is the same as depth.
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


In [27]:
#Splitting is reverse operation of Joining. We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits. If the array has less elements than required, it will adjust from the end accordingly.

#We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr,3)
print(newarr)

print(newarr[0])  #access splitted array
print(newarr[1])

lessarr = np.array_split(arr,4)  #adjusted array
print(lessarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [28]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])  #split 2D array

newarr = np.array_split(arr, 3)
#newarr = np.array_split(arr, 3,axis=1)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)  #specify axis around which array should split

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [30]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)  #alternate to axis parameter

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [31]:
#similat to hstack, vstack and dstack.. hsplit, vsplit and dsplit exist
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.vsplit(arr, 3)  

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [32]:
#Sorting means putting elements in an ordered sequence.
#This method returns a copy of the array, leaving the original array unchanged.
arr = np.array([3, 2, 0, 1])
s_arr = np.sort(arr)  #sort() will sort an array
print(arr) 
print(s_arr) 

starr = np.array(['banana', 'cherry', 'apple'])  #sort string array
print(np.sort(starr))

b_arr = np.array([True, False, True])  #sort boolean
print(np.sort(b_arr))

twoarr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(twoarr))

[3 2 0 1]
[0 1 2 3]
['apple' 'banana' 'cherry']
[False  True  True]
[[2 3 4]
 [0 1 5]]


In [33]:
#filtering arrays can be done in 2 ways
#Getting some elements out of an existing array and creating a new array out of them is called filtering.

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

#We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42   #return array with values > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[41 43]
[False False  True  True]
[43 44]


In [34]:
#Random number
from numpy import random

x = random.randint(10)  #generate random number between 1 to 100

print(x)

a = random.randint(100,size=(5)) #generate 1D array with specified shape
print(a)


b = random.randint(100, size=(3, 5)) #Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100
print(b)

9
[29 57 76 16 94]
[[51 43  6 90 56]
 [67 92 15 10 74]
 [27 11 35 22 93]]


In [35]:
y = random.rand() #generate float random number between 0 and 1
print(y)

s = random.rand(5) #5 specify shape of array
print(s)

x = random.rand(3, 5) #2D array with 3 rows 5 columns
print(x)

0.507024855474551
[0.33895638 0.14021551 0.17119551 0.84038381 0.26266991]
[[0.39072856 0.95968799 0.43079487 0.88789212 0.14353678]
 [0.54741429 0.53029113 0.39286536 0.1178519  0.21555984]
 [0.74086996 0.30070288 0.9366605  0.46083767 0.05102201]]


In [36]:
#The choice() method allows you to generate a random value based on an array of values.
#The choice() method takes an array as a parameter and randomly returns one of the values.

x = random.choice([3, 5, 7, 9])

print(x)

y = random.choice([3, 5, 7, 9], size=(3, 5)) #use choice() to return an array of random numbers
print(y)

7
[[5 9 3 3 3]
 [9 5 7 7 9]
 [3 5 9 3 5]]
